[package]
name = "proverb"
version = "0.1.4"
edition = "2021"
description = "terminal utility to print a proverb"
license = "MIT"

[dependencies]
colored = "2.0.4"
rand = "0.8.5"
terminal_size = "0.2.6"
