use rand::Rng;

pub fn bestow_wisdom() -> String {
    let mut random_number = rand::thread_rng();
    return PROVERBS[random_number.gen_range(0..PROVERBS.len())].to_owned();
}

const PROVERBS: [&str; 132] = [
    "fate has us meet from a thousand miles away",
    "hold your hand and grow old with you",
    "having love, drinking water will fill you up, without love, eating food will leave you hungry",
    "love the house with its crows (on the roof)",
    "living with love is happy, but living for love is foolish",
    "a smile is the best form of make-up",
    "give a man a fish and you feed him for a day, teach a man how to fish and you feed him for a lifetime",
    "water flows in to flow out",
    "he who asks a question might be a fool for five minutes; he who doesn't ask a question remains a fool forever",
    "fallen leaves return to their roots",
    "if you don't manage a household, you wouldn't know how expensive it is",
    "cherish a broom as if it was gold",
    "practice makes perfect",
    "teachers open the doors, but you enter by yourself",
    "learn to walk before you run",
    "hearing a hundred times doesn't compare to seeing once",
    "you cannot catch tiger cubs without entering the tiger's lair",
    "when you have a lot of friends, you don't have any real friends",
    "those with the same illness commiserate with each other",
    "the good deeds pay good recompense and the evil pays back with evil",
    "those who eat with one chopstick will stay hungry",
    "a man who eats biscuits in his bed wakes up feeling terrible",
    "after three days without reading, talk becomes flavorless",
    "a book is like a garden carried in the pocket",
    "a closed mind is like a closed book; just a block of wood",
    "it's better to be without a book than to believe a book entirely",
    "a single conversation with a wise man is worth a month's study of books",
    "if a son is uneducated, his dad is to blame",
    "a jade stone is useless before it is processed; a man is good for nothing until he is educated",
    "learning is a weightless treasure you can always carry easily",
    "true knowledge is when one knows the limitations of one's knowledge",
    "one cannot refuse to eat just because there is a chance of being choked",
    "clear conscience never fears midnight knocking",
    "once bitten by a snake, he/she is scared all his/her life at the mere sight of a rope",
    "with true friends, even water drunk together is sweet enough",
    "if you want happiness for a lifetime; help someone else",
    "better the cottage where one is merry than the palace where one weeps",
    "we count our miseries carefully, and accept our blessings without much thought",
    "you won't help shoots grow by pulling them up higher",
    "patience is a bitter plant, but its fruit is sweet",
    "if you are planning for a year, sow rice; if you are planning for a decade, plant trees; if you are planning for a lifetime, educate people",
    "if your strength is small, don’t carry heavy burdens; if your words are worthless, don’t give advice",
    "if you are patient in one moment of anger, you will escape a hundred days of sorrow",
    "parents who are afraid to put their foot down usually have children who step on their toes",
    "a diamond with a flaw is better than a common stone that is perfect",
    "a bird does not sing because it has an answer, it sings because it has a song",
    "a bit of fragrance clings to the hand that gives flowers",
    "insanity is doing the same thing in the same way and expecting a different outcome",
    "all things are difficult before they are easy",
    "time is money, and it is difficult for one to use money to get time",
    "opportunity knocks at the door only once",
    "tell me and i'll forget; show me and i may remember; involve me and i'll understand",
    "make happy those who are near, and those who are far will come",
    "one generation plants the trees, and another gets the shade",
    "there are many paths to the top of the mountain, but the view is always the same",
    "truth is more valuable if it takes you a few years to find it",
    "there is no shame in not knowing; the shame lies in not finding out",
    "coffee and love taste best when hot",
    "fall seven times, stand up eight",
    "if you can’t live longer, live deeper",
    "it takes a whole village to raise a child",
    "turn your face toward the sun and the shadows fall behind you",
    "some men go through a forest and see no firewood",
    "the tree with most leaves will not necessarily produce juicy fruit",
    "begin to weave and God will give the thread",
    "even though you know a thousand things, ask the man who knows one",
    "those who wish to sing always find a song",
    "it’s not enough to learn how to ride, you must also learn how to fall",
    "hunger is felt by a slave and hunger is felt by a king",
    "even from a foe a man may learn wisdom",
    "learning is just like sailing against the current; if you don’t advance, you will be driven back",
    "nothing in the world is difficult for one who is determined enough to achieve it",
    "learn no matter how old you grow",
    "light travels like an arrow, and time like a shuttle",
    "when you force a melon from the vines, it won’t be sweet",
    "when you drink the water, remember the spring as the source of the water",
    "misfortune tests the sincerity of friends",
    "the best time to plant a tree was twenty years ago; the second best time is now",
    "the palest ink is better than the best memory",
    "when the winds of change blow, some build walls while others build windmills",
    "the journey of a thousand miles begins with a single step",
    "be not afraid of growing slowly, be afraid only of standing still",
    "a wise man makes his own decisions, an ignorant man follows the public opinion",
    "the man who moves a mountain begins by carrying away small stones",
    "do not confine your children to your own learning, for they were born in another time",
    "the person who removes a mountain begins by carrying small stones",
    "even a hare will bite when it is cornered",
    "be not disturbed at being misunderstood; be disturbed at not understanding",
    "the gem cannot be polished without friction, nor man perfected without trials",
    "before you embark on a journey of revenge, dig two graves",
    "to talk much and arrive nowhere is the same as climbing a tree to catch a fish",
    "an inch of time is an inch of gold but you can't buy that inch of time with an inch of gold",
    "a single beam cannot support a great house",
    "a bird's feathers are not enough to cover its own body",
    "the water that bears the boat is the same that swallows it up",
    "a child’s life is like a piece of paper on which every person leaves a mark",
    "with money you can buy a house, but not a home; a clock but not time; a bed but not sleep",
    "a good book is a good friend",
    "one word can warm three winter months",
    "the higher the mountain, the greater the descent",
    "the best fighter is never angry",
    "a smile will gain you ten more years of life",
    "the heart has no wrinkles",
    "when you want to test the depths of a stream, don't use both feet",
    "kindness is the language which the deaf can hear and the blind can see",
    "a clever person turns great troubles into little ones and little ones into none at all",
    "the glory is not in never falling, but in rising every time you fall",
    "when the heart is at ease, the body is healthy",
    "better to light a candle than to curse the darkness",
    "to attract good fortune, spend a new coin on an old friend, share an old pleasure with a new friend, and lift up the heart of a true friend by writing his name on the wings of a dragon",
    "a thousand-mile journey begins with the first step",
    "the wise adapt themselves to circumstances, as water molds itself to the pitcher",
    "he who rides a tiger is afraid to dismount",
    "he who asks is a fool for five minutes, but he who does not ask remains a fool forever",
    "even the tallest tower started from the ground",
    "an ant may well destroy a whole dam",
    "one generation plants the trees, and another enjoys the shade",
    "a single conversation across the table with a wise person is worth a month's study of books",
    "patience in a moment of anger prevents a thousand days of sorrow",
    "the early bird catches the worm",
    "one who plants a tree plants hope",
    "sow seeds of kindness, and you will reap a harvest of happiness",
    "the calmest seas are where you find the strongest storms beneath",
    "even the smallest star shines in the darkness",
    "an empty vessel makes the loudest sound",
    "the moon does not care if the dog barks at it",
    "a wise man knows he knows nothing",
    "he who hurries cannot walk with dignity",
    "the tongue is but three inches long, yet it can kill a man six feet high",
    "a watched pot never boils",
    "the best mirror is an old friend",
    "an invisible thread connects those who are destined to meet"
];
